# Generated by Django 4.0.5 on 2023-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_count', models.IntegerField(default=0)),
                ('covid_count', models.IntegerField(default=0)),
                ('current_target', models.IntegerField(default=0)),
                ('control_ratio', models.FloatField(default=0.2)),
                ('site_url', models.TextField(default='http://127.0.0.1:8000')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
