# Generated by Django 4.0.5 on 2023-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Indian Mental Wellbeing Study', max_length=255)),
                ('covid_count', models.IntegerField(default=0)),
                ('suspect_count', models.IntegerField(default=0)),
                ('noise_count', models.IntegerField(default=0)),
                ('control_count', models.IntegerField(default=0)),
                ('group_ratio', models.JSONField(default=dict)),
                ('current_target', models.IntegerField(default=0)),
                ('site_url', models.TextField(default='127.0.0.1:8000')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
