# Generated by Django 4.0.5 on 2023-04-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configSolo', '0002_alter_siteconfiguration_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_url',
            field=models.TextField(default='127.0.0.1:8000'),
        ),
    ]
