# Generated by Django 4.0.3 on 2022-06-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_visit',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='participant',
            name='sessions_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='visit_time_1',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='participant',
            name='visit_time_2',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='participant',
            name='visit_time_3',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='participant',
            name='visit_time_4',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='participant',
            name='visit_time_5',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='participant',
            name='visit_time_6',
            field=models.DateTimeField(default=None),
        ),
    ]
