# Generated by Django 4.0.3 on 2022-06-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_participant_last_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='department',
        ),
    ]
