# Generated by Django 4.0.3 on 2022-06-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='session_num',
            field=models.IntegerField(default=0),
        ),
    ]
