# Generated by Django 4.0.5 on 2022-07-23 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_codes_session_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_email',
            field=models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0)),
        ),
    ]
