# Generated by Django 4.0.5 on 2023-04-16 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_participant_is_verified_participant_last_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codes',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codes',
            name='ref',
            field=models.CharField(default='noref', max_length=30),
        ),
        migrations.AddField(
            model_name='participant',
            name='cloudresearch_aid',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_colorBlind',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_colorTested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_eligible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='longitudinal_enrollment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='ref',
            field=models.CharField(default='noref', max_length=30),
        ),
        migrations.CreateModel(
            name='waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('covid_history', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
