# Generated by Django 4.0.5 on 2022-08-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_participant_is_verified_participant_last_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
