# Generated by Django 4.0.5 on 2022-10-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_codes_ref_participant_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_colorBlind',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_colorTested',
            field=models.BooleanField(default=False),
        ),
    ]
