# Generated by Django 4.0.5 on 2022-08-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_participant_is_colorblind_participant_is_colortested'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='codes',
        #     name='ref',
        #     field=models.CharField(default='noref', max_length=30),
        # ),
    ]
