# Generated by Django 4.0.5 on 2022-10-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_participant_is_colorblind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='is_colorBlind',
            field=models.BooleanField(default=True),
        ),
    ]
