# Generated by Django 4.0.5 on 2022-10-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_no_change'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='participant',
        #     name='is_colorTested',
        #     field=models.BooleanField(default=False),
        # ),
    ]
