# Generated by Django 4.0.5 on 2023-03-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_participant_is_eligible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='is_eligible',
        ),
    ]
