# Generated by Django 4.0.5 on 2023-03-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_participant_is_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_eligible',
            field=models.IntegerField(default=0),
        ),
    ]
