# Generated by Django 4.0.5 on 2023-04-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_waitlist'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='participant',
        #     name='cloudresearch_aid',
        #     field=models.CharField(default='', max_length=30),
        # ),
    ]
