# Generated by Django 4.0.5 on 2023-04-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_participant_cloudresearch_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
