# Generated by Django 4.0.5 on 2023-05-17 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0022_codes_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='screen_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.BooleanField(default=False)),
                ('english', models.BooleanField(default=False)),
                ('covid_testPositive', models.BooleanField(default=False)),
                ('covid_symptoms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
